use_frameworks!

platform :ios, '8.3'

target 'ScaledCenterCarousel_Example' do
  pod 'ScaledCenterCarousel', :path => '../'

  target 'ScaledCenterCarousel_Tests' do
    inherit! :search_paths

	pod 'Specta'
	pod 'Expecta'
  end
end
